### ISSUE TITLE
Signup - Password Field Displays Plain Text During Signup

### ISSUE THREAD

**Issue by ashrafiucse** [theihasan/geezap#18]
**Description:**
During the signup process on the job search website, the password entered in the password field is displayed in plain text rather than being masked or encrypted. This exposes sensitive user information to potential threats, such as shoulder surfing or unauthorized access.

**Severity:** High

**Priority:** Critical

**Steps to Reproduce:**

1. Navigate to the signup page.
2. Enter a password in the password field.
3. Observe that the password is displayed in plain text instead of being masked (e.g., as dots or asterisks).

**Expected Behavior:** 
The password should be masked in the field by default (e.g., displayed as dots or asterisks) to prevent exposure. An optional "show/hide" toggle can be provided for user convenience, with the default state being "hidden."

**Actual Behavior:**
The password is visible in plain text as the user types, posing a security risk.

![image](https://github.com/user-attachments/assets/3b7a2d7b-0e0f-4ca7-842d-af4110341c82)

**Comment by theihasan** [comment]
issue fixed
