### ISSUE TITLE
SignUp - Form Submission Allowed Without Agreeing to Terms and Conditions

### ISSUE THREAD

**Issue by ashrafiucse** [theihasan/geezap#19]
**Description:**
During the account creation process, the user can submit the form without selecting the "Terms and Conditions" checkbox. This allows users to bypass agreeing to the platform's terms, which is both a functional issue and a potential legal compliance risk.

**Severity:** Medium
**Priority:** High

**Steps to Reproduce:**

1. Navigate to the account creation (signup) page.
2. Fill out all the required fields except for the "Terms and Conditions" checkbox.
3. Click the "Submit" button.
4. Observe that the form is submitted successfully without requiring the user to agree to the terms.

**Expected Behavior:**
The "Submit" button should be disabled or the form should display an error message unless the "Terms and Conditions" checkbox is selected.

**Actual Behavior:**
The form is submitted successfully even if the "Terms and Conditions" checkbox is not selected.

![image](https://github.com/user-attachments/assets/8b2b6bec-548a-4933-b9fd-6ba3a30b9106)

**Comment by theihasan** [comment]
issue fixed
