### ISSUE TITLE
Category - "No Jobs Found" Displayed on Category Click Without Skill Set in User Profile

### ISSUE THREAD

**Issue by ashrafiucse** [theihasan/geezap#24]
**Description:**
When a user clicks on the "Categories" link in the navbar, a list of job categories with the number of available positions is displayed. However, upon selecting any category, the system displays "No jobs found matching your criteria," even though the user has not set any skill set in their profile. This creates confusion, as all job listings in the selected category should be visible by default if no filters are applied.

**Severity:** High
**Priority:** High

**Steps to Reproduce:**

1. Navigate to the website and log in.
2. Ensure that the user profile does not have any skills set.
3. Click on the "Categories" link in the navbar.
4. Observe the list of job categories with the number of available positions.
5. Click on any category.
6. Observe that the system displays "No jobs found matching your criteria."

**Expected Behavior:**
When a user selects a job category:

1. All available jobs in the selected category should be displayed by default.
2. If no skill set or filter is applied, the system should display the full list of jobs matching the category.
3. A message should appear prompting the user to refine the results by updating their profile or applying filters, but jobs should still be visible.

**Actual Behavior:**
The system displays "No jobs found matching your criteria," even though jobs exist in the selected category and the user has not applied any filters.

![image](https://github.com/user-attachments/assets/21b5aa89-4a8d-4c90-adb1-a34e16898638)

![image](https://github.com/user-attachments/assets/4206261f-dd75-41b2-a046-3ba1b9868b40)

**Comment by theihasan** [comment]
issue resolved
