### ISSUE TITLE
Forget Password - System Crash on Password Reset Email Request

### ISSUE THREAD

**Issue by ashrafiucse** [theihasan/geezap#25]
**Description:**
The system crashes when the user inputs their email address and clicks the "Send" button to request a password reset email. This disrupts the password recovery process and prevents users from regaining access to their accounts.

**Severity:** Critical
**Priority:** High

**Steps to Reproduce:**

1. Navigate to the "Forgot Password" or "Password Reset" page.
2. Enter a valid or invalid email address in the email input field.
3. Click the "Send" button.
4. Observe that the system crashes instead of processing the request or showing a relevant message.

**Expected Behavior:**
When the user clicks the "Send" button after entering an email address:

1. The system should validate the input email format.
2. If the email is associated with an account, a password reset email should be sent, and a success message should be displayed (e.g., "A password reset email has been sent to your email address.").
3. If the email is not associated with any account, an error message should appear (e.g., "Email not found.").
4. The system should handle all cases gracefully without crashing.

**Actual Behavior:**
The system crashes upon clicking the "Send" button, making the feature unusable.

Reference: https://flareapp.io/share/NPL1bk27

**Comment by theihasan** [comment]
SMTP is not set up so far. That's why this error occurs
